// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJfcE4rCVJiq97wKWyM4pdW6BEYL4EClE',
    appId: '1:914692562352:web:a0c700686d08a813fc8a75',
    messagingSenderId: '914692562352',
    projectId: 'caramel-1-5d932',
    authDomain: 'caramel-1-5d932.firebaseapp.com',
    storageBucket: 'caramel-1-5d932.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvLvXhOAxQyXusuCyn-BsBaNXU9zeCjb8',
    appId: '1:914692562352:android:570d6ea5d034a2f8fc8a75',
    messagingSenderId: '914692562352',
    projectId: 'caramel-1-5d932',
    storageBucket: 'caramel-1-5d932.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOvrSSv9ibEmG73ZxILP-9nT3CSTLY_uQ',
    appId: '1:914692562352:ios:b89e437d011eff84fc8a75',
    messagingSenderId: '914692562352',
    projectId: 'caramel-1-5d932',
    storageBucket: 'caramel-1-5d932.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOvrSSv9ibEmG73ZxILP-9nT3CSTLY_uQ',
    appId: '1:914692562352:ios:02154b0914847455fc8a75',
    messagingSenderId: '914692562352',
    projectId: 'caramel-1-5d932',
    storageBucket: 'caramel-1-5d932.appspot.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
